### ISSUE TITLE
Test AWS Step Functions workflows using mocks

### ISSUE THREAD

**Issue by rohanmeh** [aws-samples/serverless-test-samples#151]

**Comment by dancfox** [comment]
We have one published example here:

https://github.com/aws-samples/serverless-test-samples/tree/main/java-test-samples/step-functions-local

**Comment by rohanmeh** [comment]
@dancfox this task is for the Typescript version of that pattern using Jest instead of JUnit. I'm trying to use the issue labels to differentiate between languages.

**Comment by dancfox** [comment]
Understood.

**Comment by brnkrygs** [comment]
Being worked by volunteer
