### ISSUE TITLE
{   "detail-type": ["customer_account_created", "customer_account_updated", "consumer_created", "consumer_updated"],   "source": ["ssrm"],   "data": {     "consumer": [{       "my_id": {         "!": "null"       }     }]   } }

### ISSUE THREAD

**Issue by lasanthars** [aws-samples/serverless-test-samples#212]
### Runtime

Java

### Language

English

### Language

SAM

### Application Code

/src/app.py

### Unit Test Code

/src/app.py

### Integration Test Code

/src/app.py

**Comment by brnkrygs** [comment]
Looks like this may have been created by accident. Closing for now.
